spring:
  application:
    name: utsav

  profiles:
    default: dev

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false


utsav:
  events:
    default-limit: 5
    max-limit: 100


server:
  port: 8080



